# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d326f292adce7ac67240cc177068ef98724535771fcc1f87972c9681315a4e838a79ff0d1b3d467bdc3d5de36166caf419ba712f4ca7f9ff2c4dca0f72270c

test:
  secret_key_base: 54634f1756fb189660460dbec843cd9651047477606401c0b04bdc317ff23732ca8569f66a483916857edffb7558b0f8be91e522b8af6289ee7391dfa809506c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 05e114a1d4d16a7db5db10d86821d44596fadc0a8b9272a78eab26baf4b127b8f17f19f6f58590ca71aa53317db8a10e8c1a02952a3f910b8d12f1ec243b5d32 
